### ISSUE TITLE
Support code SS03 error.

### ISSUE THREAD

**Issue by solsahar** [Eltion/Snapchat-SSL-Pinning-Bypass#2]
Hey, I just patched the latest version of snapchat (a beta version) and got it running on Nox player. I am now getting error SS03.
![image](https://user-images.githubusercontent.com/32788382/211284115-8682f9dc-630f-4d98-af8e-85ff746d3669.png)

It doesn't matter if I try to log in or anything, it just breaks. Thanks!

**Comment by Eltion** [comment]
It seems like the snapchat is detecting that the apk is patched. I'll see if I can bypass that

**Comment by Eltion** [comment]
@solsahar, It seems that snapchat now is checking the apk signature in the backend, I think it's possible to bypass this, I'll soon release a new version of the script :)

**Comment by solsahar** [comment]
Awesome thank you so much! Do you have discord i could contact you on? I’ve been trying to find a way to bypass ssl pinning for months now but haven’t really had the knowledge to do so. I really can’t explain how much i appreciate you. Thanks!

**Comment by Eltion** [comment]
@solsahar Problem should be solved now. I just created a now release here: 
https://github.com/Eltion/Snapchat-SSL-Pinning-Bypass/releases/tag/v12.16.0.28

I don't have discord but you can reach me in telegram: @eltimusa4

**Comment by solsahar** [comment]
I appreciate you so much, thank you!

**Comment by Titanium2099** [comment]
It no longer works and now detects that it is patched...
