### ISSUE TITLE
how to baypas?

### ISSUE THREAD

**Issue by ysf72byk** [Eltion/Snapchat-SSL-Pinning-Bypass#3]
How do you bypass these programs, can you make a video narration?

**Comment by Eltion** [comment]
If you mean how to use this library you can check out this video I did for instagram but is the same with snapchat:
https://user-images.githubusercontent.com/18504798/177385493-5fd557bd-cb59-4342-b6d8-8b70262e6c06.mp4

**Comment by ysf72byk** [comment]
Do you have any training on ssl pinning bypass?

**Comment by Eltion** [comment]
@ysf72byk no not really
