### ISSUE TITLE
Login and register not bypassed

### ISSUE THREAD

**Issue by optickavarka** [Eltion/Snapchat-SSL-Pinning-Bypass#4]
Tested on Nox emulator with patched apk (no root) provided from your repository, using charles proxy, what you think i should change?
Tested with rooted nox as well, no luck on the login and register

**Comment by Eltion** [comment]
Use mitmproxy instead, that should solve your problem :)

**Comment by optickavarka** [comment]
ok will let you know, thanks

**Comment by optickavarka** [comment]
Thank you very much for this, i learned a lot, and yes it works with mitmproxy. If you use discord i will be glad if we can talk a bit.

**Comment by Eltion** [comment]
@optickavarka, I don't use discord but I'm available at telegram: @eltimusa4.
Thanks a lot for confirming that it works with mitmproxy.
