### ISSUE TITLE
Latest release request

### ISSUE THREAD

**Issue by TheTottyApple** [Eltion/Snapchat-SSL-Pinning-Bypass#5]
Hey Eltion!

just wondering if you have the time to look at 12.19! For some reason some requests are going through but other ones (like messages for example) aren't being shown at all in my interceptor, not even a server refuse.

much appreciated!
-moey

**Comment by TheTottyApple** [comment]
nvm latest is working when using mitmproxy! I'm assuming the ca cert being signed is mitmproxy's and that's why no other interceptors work, really appreciate what you're doing here 😄 


-moey

**Comment by Eltion** [comment]
@TheTottyApple actually I'm not sure why it's only working for mitmproxy, I have not patched the apk using mitmproxy's certificate, I think the problem is not really about ssl pinning. I'll put an info message in the README that currently this is only working with mitmproxy. 

Thanks

**Comment by TheTottyApple** [comment]
appreciate the response 😄, weird okay at first I thought you used mitm's cert but I guess not, I'll try burp whenever I get the chance but I know HTTPToolkit didn't work

-moey
