### ISSUE TITLE
Requests look like partial encrypted

### ISSUE THREAD

**Issue by senolatac** [Eltion/Snapchat-SSL-Pinning-Bypass#7]
Is there a way to decrypt them?

<img width="870" alt="Screen Shot 2023-03-05 at 20 28 31" src="https://user-images.githubusercontent.com/27292083/223415889-0f7ad8e7-b860-4a46-a860-e6c0741bbfca.png">

**Comment by Eltion** [comment]
@senolatac this is outside the scope of this repo,

**Comment by traffisco** [comment]
> Is there a way to decrypt them?
> 
> <img alt="Screen Shot 2023-03-05 at 20 28 31" width="870" src="https://user-images.githubusercontent.com/27292083/223415889-0f7ad8e7-b860-4a46-a860-e6c0741bbfca.png">

Hi,
What proxy do you use? Because it doesn't look like mitmp
